// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxL4W3C2N9Si3HPcbdl8ksJaOW41OR-Hs',
    appId: '1:470039689764:android:b7311b92b9f8910e91b6b1',
    messagingSenderId: '470039689764',
    projectId: 'mentalhealthapp-bcffd',
    storageBucket: 'mentalhealthapp-bcffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5BggEXrNwRA6rFYoQRBevDzxIJN29jg',
    appId: '1:470039689764:ios:78e5e5147a707bd091b6b1',
    messagingSenderId: '470039689764',
    projectId: 'mentalhealthapp-bcffd',
    storageBucket: 'mentalhealthapp-bcffd.appspot.com',
    androidClientId: '470039689764-qvjjdlohd5r669e4g4bc87p8n61cnd6v.apps.googleusercontent.com',
    iosClientId: '470039689764-r5rhjdpb01cnne7jrovrln9p5a34bj81.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalHealthApp',
  );
}
